### ISSUE TITLE
[Planning] - 도메인 별 `endpoint` 작동을 확인한다.

### ISSUE THREAD

**Issue by jbw9964** [prgrms-be-devcourse/NBE1_2_Team10#108]
# 🏷 진행할 작업들

<details><summary> 유저 관련 API 작동 확인 (User)</summary>

- [x] 모두 확인함?

| `HTTP Method` | `API`            |     설명     | 동작 확인 여부 |
|:-------------:|:-----------------|:----------:|:--------:|
|    `POST`     | `/users/signup`  |    회원가입    |    V      |
|    `POST`     | `/users/signin`  |    로그인     |       V   |
|    `PATCH`    | `/users/update`  | 유저 정보 업데이트 |   V       |
|     `GET`     | `/users/reissue` | `Access Token` 재발급 |     V     |
|   `DELETE`    | `/users/signout` |    로그아웃    |       V   |
|   `DELETE`    | `/users/delete`  |   유저 삭제    |        V  |

---

</details>

<details><summary> 영화 관련 API 작동 확인 (Movie)</summary>

- [x] 모두 확인함?

| `HTTP Method` | `API`                   |      설명       | 동작 확인 여부 |
|:-------------:|:------------------------|:-------------:|:--------:|
|     `GET`     | `/movies/list`          | 메인 페이지의 영화 목록 |    V      |
|     `GET`     | `/movies/search`        |   영화 통합 검색    |      V    |
|     `GET`     | `/movies/genre/{genre}` |   영화 장르 검색    |   V       |
|     `GET`     | `/movies/{movieId}`     |   영화 상세 페이지   |      V    |

---

</details>

<details><summary>마이 페이지 API 작동 확인 (MyPage)</summary>

- [x] 모두 확인함?

| `HTTP Method` | `API`           |    설명     | 동작 확인 여부 |
|:-------------:|:----------------|:---------:|:--------:|
|     `GET`     | `/users/mypage` | 유저 마이 페이지 |      V    |

---

</details>

<details><summary>영화 찜 API 작동 확인 (Dib)</summary>

- [x] 모두 확인함?

| `HTTP Method` | `API`                   |     설명     | 동작 확인 여부 |
|:-------------:|:------------------------|:----------:|:--------:|
|     `PUT`     | `/movies/{movieId}/dib` | 영화 찜 등록/취소 |    V      |

---

</details>

<details><summary>한줄평 관련 APi 작동 확인 (Comment)</summary>

- [x] 모두 확인함?

| `HTTP Method` | `API`                                            |     설명     | 동작 확인 여부 |
|:-------------:|:-------------------------------------------------|:----------:|:--------:|
|     `GET`     | `/movies/{movieId}/comments`                     |   한줄평 조회   |    V      |
|    `POST`     | `/movies/{movieId}/comments`                     |   한줄평 작성   |    V      |
|   `DELETE`    | `/movies/{movieId}/comments/{commentId}`         |   한줄평 삭제   |   V       |
|    `POST`     | `/movies/{movieId}/comments/{commentId}/like`    |  한줄평 좋아요   |    V      |
|   `DELETE`    | `/movies/{movieId}/comments/{commentId}/like`    | 한줄평 좋아요 취소 |    V      |
|    `POST`     | `/movies/{movieId}/comments/{commentId}/dislike` |  한줄평 싫어요   |    V      |
|   `DELETE`    | `/movies/{movieId}/comments/{commentId}/dislike` | 한줄평 싫어요 취소 |    V      |

---

</details>

<details><summary>영화 후기 포스팅 관련 API 작동 확인 (Review)</summary>

- [x] 모두 확인함?

| `HTTP Method` | `API`                                  |        설명         | 동작 확인 여부 |
|:-------------:|:---------------------------------------|:-----------------:|:--------:|
|     `GET`     | `/movies/{movieId}/reviews/list`       |     포스팅 목록 조회     |          |
|     `GET`     | `/movies/{movieId}/reviews/{reviewId}` |   포스팅 상세 내용 조회    |          |
|    `POST`     | `/movies/{movieId}/reviews`            |      포스팅 생성       |
|    `PATCH`    | `/movies/{movieId}/reviews/{reviewId}` |      포스팅 수정       |          |
|   `DELETE`    | `/movies/{movieId}/reviews/{reviewId}` |      포스팅 삭제       |          |
|    `PATCH`    | `/movies/{movieId}/reviews/{reviewId}/like` | 포스팅 좋아요 또는 좋아요 취소 |          |

---

</details>

<details><summary>영화 후기 포스팅 댓글 관련 API 작동 확인 (Review Comment)</summary>

- [x] 모두 확인함?

| `HTTP Method` | `API`                                                            |        설명        | 동작 확인 여부 |
|:-------------:|:-----------------------------------------------------------------|:----------------:|:--------:|
|     `GET`     | `/movies/{movieId}/reviews{reviewId}/comments`                   |     부모 댓글 조회     |          |
|     `GET`     | `/movies/{movieId}/reviews{reviewId}/comments/{groupId}`         |     자식 댓글 조회     |          |
|    `POST`     | `/movies/{movieId}/reviews{reviewId}/comments`                   |      댓글 생성       |          |
|    `PATCH`    | `/movies/{movieId}/reviews{reviewId}/comments/{reviewCommentId}` |      댓글 수정       |          |
|   `DELETE`    | `/movies/{movieId}/reviews{reviewId}/comments/{reviewCommentId}` |      댓글 삭제       |          |
|    `PATCH`    | `/movies/{movieId}/reviews{reviewId}/comments/{reviewCommentId}/like` | 댓글 좋아요 또는 좋아요 취소 |          |

---

</details>

<details><summary>이미지 업로드 관련 API 작동 확인 (CkEditor)</summary>

- [x] 모두 확인함?

| `HTTP Method` | `API`                    |        설명         | 동작 확인 여부 |
|:-------------:|:-------------------------|:-----------------:|:--------:|
|    `POST`     | `/ckeditor/image-upload` | CK Editor 이미지 업로드 |          |

</details>

---

# 📝 구체적인 작업 설명

모든 API 를 `Postman` 으로 잘 작동하는지 확인합니다.

---

# ⏩ 계획 완료 후 예상되는 작업

동작 시연 순서 생각하기

---

**Comment by jbw9964** [comment]
### 유저 관련 API 동작 확인

- 회원가입, 유저 정보 업데이트 시 필요한 request body 가 동일함. 더불어 body 에 어떤 정보가 반드시 필요한지 파악하기 어려움. 각 요청별 DTO 를 따로 만드는게 좋아보임.

- 회원가입 : 이메일 중복시 500 코드 발생

- 로그인 : 존재하지 않는 유저로 로그인하면 401 발생 (email, pw)

- 로그인 : 로그인 되었으면 응답 메시지가 있으면 좋겠음. (현재 : 그냥 200)

- 유저 정보 업데이트 : 정보 수정하려면 client 에서 유저의 정확한 UUID 필요함 (500). 거기다 자신만 정보 수정 가능토록 하는 로직 없음.

- 유저 삭제 시 redis 에 저장된 refreshToken 삭제 되는거?

- accessToken 을 요청 헤더에 넣을 때 헤더 키가 "accessToken" 이 아니라 "Authorization" 이면 좋겠음.

**Comment by jbw9964** [comment]
### 영화 관련 API 동작 확인

- `영화 상세 페이지` 접근 시 `accessToken` 필요한 버그 발생 `(SecurityConfig 에서 /movies/* permitAll 해야 함. 현재 : /movies/)`

**Comment by hgh1472** [comment]
영화쪽은 어제 리팩토링하면서 전체적으로 한번 확인해서 현재 Merge된 develop에서는 실행 될 것 같습니다!

**Comment by jbw9964** [comment]
### 마이 페이지 API 동작 확인

- `마이 페이지` 접근 시, 사용자 정보를 `Security Context` 에서 가져오는 로직 없음. 그래서 `500` 발생

**Comment by jbw9964** [comment]
### 한줄평 관련 API 동작 확인

- `Swagger` 에 `한줄평 삭제` 설명 공란

**Comment by jbw9964** [comment]
### 영화 후기 포스팅 댓글 관련 API 동작 확인

- `포스팅 목록 조회` 시 `page` `query param` 부재시 `"(400) Access Token 이 존재하지 않습니다."` 설명이 옴. `(잘못된 응답)`

**Comment by sunnism03** [comment]
마이페이지, 찜 userId 불러오는 로직 추가해서 PR 날려놨는데 
나머지 에러들도 그 브랜치에서 수정해보겠습니다!

**Comment by jbw9964** [comment]
### 영화 후기 포스팅 댓글 관련 API 동작 확인

- `댓글 생성` 시 `@Transactional` 설정으로 인한 오류 발생, (500)
    - `@Transactional(readOnly = true)` 때문에 `Connection is read-only. Queries leading to data modification are not allowed` 발생

**Comment by TrixieL20** [comment]
자신만 정보를 수정하도록 local에서 수정했던 부분이 업데이트가 안 되어 있어서 push 진행했고 회원 탈퇴 시 rt 삭제 부분이 빠져 있어 추가 수정해 올렸습니다. #121
