### ISSUE TITLE
[Bug] - `(devlop)` 회원 가입 시 존재하는 계정과 중복된 이메일을 넣으면 `500` 코드가 발생합니다.

### ISSUE THREAD

**Issue by jbw9964** [prgrms-be-devcourse/NBE1_2_Team10#112]
# ❗❗ 발견한 버그에 대한 설명

회원 가입 시 이전 `DB` 에 중복되는 이메일로 회원가입 시 `500, internal server error` 가 발생합니다.

---

# ✅ 정상적인 실행

이메일이 중복되었다는 메시지

---

# 📤 문제 상황 공유

<p align="center">
    <img src="https://github.com/user-attachments/assets/cd531266-3c5d-40d9-91bf-25a92d1124b6" width=80%>
</p>

---

# 🖥 버그가 발생한 기기 정보

---

# 📝 추가적인 정보

---

**Comment by hgh1472** [comment]
해결해서 PR 올렸습니다!
