### ISSUE TITLE
[Invalid] - `(develop)` 로그인 시 존재하지 않는 정보로 로그인하면 `401` 응답이 발생합니다.

### ISSUE THREAD

**Issue by jbw9964** [prgrms-be-devcourse/NBE1_2_Team10#113]
# ⚠ 요청 개요

- **담당자 :**
    - 유저 관련 구현 : @TrixieL20, @sunnism03  
    - 공통 응답 관련 구현 : @hgh1472 

- **중요도 : 중**
- **수정 기한 : ?** 

---

# 📑 수정이 필요한 내용

1. **위치:** 

`UserController` 어딘가

2. **현재 상태** 

DB 에 존재하지 않는 로그인 정보로 로그인 시, 응답으로 `401` 코드가 뜹니다.

<p align="center">
    <img src="https://github.com/user-attachments/assets/99d1d00a-c1d1-4e34-b185-899d1dd84707" width=80%>
</p>

3. **원하는 변경 방향성** 

유저 정보가 존재하지 않는다는 메시지가 있으면 좋겠습니다.

---

# ⚔ 변경 요청 사유

응답을 확인할 때 헷갈립니다.

---

# 📚 기타 참고 사항

---

**Comment by hgh1472** [comment]
이 부분은 제가 해결해볼게요!

**Comment by hgh1472** [comment]
#117 PR에서 수정하였습니다!
