### ISSUE TITLE
[Bug] - `(develop)` 회원가입 시 유저 비밀번호가 encrypt 되지 않고 `DB` 에 저장됩니다.

### ISSUE THREAD

**Issue by jbw9964** [prgrms-be-devcourse/NBE1_2_Team10#114]
# ❗❗ 발견한 버그에 대한 설명

회원 가입 시 유저 비밀번호가 `encrypt` 되지 않고 그대로 `DB` 에 저장됩니다.

---

# ✅ 정상적인 실행

Spring security 의 encrypt 로 변환 후 저장

---

# 📤 문제 상황 공유

비밀번호 `Abc@1234` 가 그대로 저장됨

<p align="center">
    <img src="https://github.com/user-attachments/assets/cd531266-3c5d-40d9-91bf-25a92d1124b6" width=80%>
</p>

<p align="center">
    <img src="https://github.com/user-attachments/assets/32d9a025-9e35-48c6-b435-4ba9dd2d0062" width=80%>
</p>

---

# 🖥 버그가 발생한 기기 정보

---

# 📝 추가적인 정보

---

**Comment by hgh1472** [comment]
`UserServiceImpl`에서 BcryptPasswordEncoder` 주입받아서 저장시에 사용하면 될 것 같습니다!
```java
.userPw(passwordEncoder.encode(UserDTO.getUserPw()))
```

**Comment by hgh1472** [comment]
이것도 같이 해결할게요!

**Comment by hgh1472** [comment]
#117 PR에서 수정하였습니다!
