### ISSUE TITLE
[Invalid] - `(develop)` 유저 정보 수정 시, `client` 에서 유저 `UUID` 도 제공해야 합니다.

### ISSUE THREAD

**Issue by jbw9964** [prgrms-be-devcourse/NBE1_2_Team10#115]
# ⚠ 요청 개요

- **담당자 : @TrixieL20 , @sunnism03** 
- **중요도 : 중**
- **수정 기한 : ?** 

---

# 📑 수정이 필요한 내용

1. **위치:** 

- `UserController`
https://github.com/prgrms-be-devcourse/NBE1_2_Team10/blob/1a9ff2101624c4886c31f1f284684caf855642eb/application/src/main/java/core/application/users/controller/UserController.java#L82

- `UserServiceImpl`
https://github.com/prgrms-be-devcourse/NBE1_2_Team10/blob/1a9ff2101624c4886c31f1f284684caf855642eb/application/src/main/java/core/application/users/service/UserServiceImpl.java#L72

3. **현재 상태** 

`/user/update` 요청 시 `client` 가 `UserDTO` 를 `body` 로 제공해야 하고, `UUID` 를 제공해 줘야 합니다.

4. **원하는 변경 방향성** 

`UUID` 가 아닌 `userEmail` 등을 이용해 로직을 바꿉니다.
또는 `Token` 을 이용한 로직으로 바꿉니다.

---

# ⚔ 변경 요청 사유

`/user/update` 요청 시 `client` 가 `UserDTO` 를 `body` 로 제공해야 합니다.

```java
public class UserDTO {
    private UUID userId;
    @Email
    @Pattern(regexp = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$", message="이메일 주소 양식을 확인해주세요")
    private String userEmail;
    @Pattern(regexp = "^(?=.*[a-zA-Z])(?=.*[!@#$%^*+=-])(?=.*[0-9]).{8,15}$")
    private String userPw;
    private UserRole role;
    private String alias;
    @Pattern(regexp = "^010-\\d{4}-\\d{4}$")
    private String phoneNum;
    private String userName;
}
```

그런데 유저 정보 확인 로직을 보니 `UserDTO` 의 `UUID userId` 를 통해 정보를 가져오는 것을 확인하였습니다.

`UUID` 같은 경우 `DB` 에서 생성되는 값이며, 유저가 회원가입한 당시만 응답으로 볼 수 있습니다.
때문에 이를 이용해 유저 정보를 업데이트 하는 건 `client` 가 기억하기 어렵다고 생각해 수정 건의 드립니다.

---

# 📚 기타 참고 사항

---

**Comment by TrixieL20** [comment]
token을 받아 수정할 수 있도록 수정해두겠습니다
