### ISSUE TITLE
[Invalid] - `(develop)` `JWT` 만료 시 `500` 응답을 뱉어냅니다.

### ISSUE THREAD

**Issue by jbw9964** [prgrms-be-devcourse/NBE1_2_Team10#116]
# ⚠ 요청 개요

- **담당자  :**
    - `JWT` : @TrixieL20 
    - `공통 응답` : @hgh1472 
 
- **중요도 : 중**
- **수정 기한 : ?** 

---

# 📑 수정이 필요한 내용

1. **위치:** 

2. **현재 상태** 

`Access Token` 이 필요한 요청을 처리 중, 주어진 토큰이 만료된 경우 `500, internal server error` 를 뱉어냅니다.

<p align="center">
    <img src="https://github.com/user-attachments/assets/e0358db7-d494-43ba-9b8d-4d1dcd0f1bde" width=80%>
</p>

<p align="center">
    <img src="https://github.com/user-attachments/assets/fa9e78e1-26ac-4253-8b71-840ba908467b" width=80%>
</p>

3. **원하는 변경 방향성** 

토큰이 만료되었다는 응답이 보여졌으면 좋겠습니다.

---

# ⚔ 변경 요청 사유

테스트 할 때 헷갈립니다.

---

# 📚 기타 참고 사항

---

**Comment by hgh1472** [comment]
#117 PR에서 수정하였습니다!
