### ISSUE TITLE
[Planning] - `MyBatis` 에서 `JPA` 로 마이그레이션 계획

### ISSUE THREAD

**Issue by jbw9964** [prgrms-be-devcourse/NBE1_2_Team10#136]
# 🏷 진행할 작업 개요

`MyBatis` 에서 `JPA` 로 마이그레이션 예정 사항입니다.

**저희는 `Spring profile` 을 이용해 프로필 설정 만으로 `MyBatis`, `JPA` 프레임웍을 선택할 수 있고자 합니다.**

> Spring profile 공식 문서 : [`link`](https://docs.spring.io/spring-boot/reference/features/profiles.html)
> 
> 참고하기 괜찮은 자료
> - [`Spring의 @Profile에 대해서 알아보자`](https://velog.io/@tidavid1/Spring%EC%9D%98-Profile%EC%97%90-%EB%8C%80%ED%95%B4%EC%84%9C-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90)
> - [`Spring Profiles example`](https://mkyong.com/spring/spring-profiles-example/)

저희 `application.profile` 을 보면 아래처럼 `spring.profiles.active=mybatis` 라는 설정이 있습니다.

<p align="center">
    <img src="https://github.com/user-attachments/assets/804c2c51-47e3-44e4-82f8-6bc3f2bd165a" width="80%" height="80%">
</p>

`spring.profiles.active` 설정으로 현재 앱을 실행할 프로필을 선택할 수 있고, 이를 통해 **`특정 상황에서 Bean 을 추가하거나 다른 속성값을 설정`** 할 수 있습니다.

현재 `develop` 에는 `MyBatisConfig` 클래스에만 스프링 프로필이 사용되고 있습니다.

<p align="center">
    <img src="https://github.com/user-attachments/assets/72ce6b65-99d8-4b11-8715-3c932104c455" width="40%" height="40%">
</p>

저희는 이 스프링 프로필을 이용해 `'JPA 프레임웍을 이용'` 하는 `JPA 프로필`, `'MyBatis 프레임웍을 이용'` 하는 `MyBatis 프로필` 을 구현할 생각입니다.

> **즉, `MyBatis` 코드를 남겨 두면서 `JPA` 코드를 추가하고, 
> 이를 `프로필` 로 구분해 실행 시에만 우리가 선택할 수 있도록 만들 예정입니다.**

---

# 📝 구체적인 작업 설명

현재 저희 `Repository` 들은 대부분 `MyBatis mapper` 를 이용하는 구현체를 주입받고, 그 구현체를 `Bean` 으로 등록하는 형태로 사용되고 있습니다.

<p align="center">
    <img src="https://github.com/user-attachments/assets/268b9028-5d6b-4936-a457-00659a1406b5" width="80%" height="80%">
</p>

<p align="center">
    <img src="https://github.com/user-attachments/assets/85edeceb-8476-4a63-8cd0-fa18bbf85cd0" width="80%" height="80%">
</p>

만약 위 `CachedMovieRepositoryImpl` 에 아래처럼 `profile` 설정을 넣고 실행하면 앱이 실행될 수 없습니다.

<p align="center">
    <img src="https://github.com/user-attachments/assets/5e89a9bb-bcbd-4a11-82c9-1ca7fc08a328" width="80%" height="80%">
</p>

<p align="center">
    <img src="https://github.com/user-attachments/assets/abf25f87-892e-4b93-b86f-c55a0d1be22c" width="80%" height="80%">
</p>

즉, `profile` 설정으로 `Spring` 에 등록되는 `Bean` 을 관리할 수 있다는 것입니다.

이를 이용해 저희는 다음 작업을 수행하려고 합니다.

#### **3. `spring profile` 에 따라 이 둘을 자유롭게 선택할 수 있도록 배포**

---

# 💬 예상되는 작업 Step

---

> ## **1. `MyBatis` 가 사용되는 구현체를 `mybatis` 프로필 에서만 사용되도록 변경**

- **A. 원활한 작업을 위해선 기존 `MyBatis` 를 이용하는 코드가 철저히 분리되어야 합니다.**

    어떤 방식으로 분리할 지는 논의중이나, 아래 2 가지 방식 중 한가지로 진행될 것 같습니다.

    1. `MyBatisConfig` 처럼 어떤 `config` 폴더에 모두 몰아넣기
    2. 각 도메인 별 `repository` 폴더 내 `mybatis` 폴더에 각각 몰아넣기

- **B. 또한 분리 후, 각 `MyBatis` 구현체를 `@Profile` 을 붙이기만 할 지, 아니면 하나의 `Config` 파일에서 `@Bean` 처리를 할 지 논의중입니다.**

- **C. 마지막으로 `JPA` 추가 후 앱이 정상 실행되는지 파악하기 위해, `Test code` 들에 대한 대대적인 `Refactoring` 이 진행될 것 같습니다.**

---

> ## **2. `JPA` 를 이용하는 `repository` 구현체를 `jpa` 프로필 에서만 사용되도록 추가**

- **1. `Entity` 를 `JPA` 에서 사용할 수 있도록 변경합니다.**

    이 때 기존 `Entity` 클래스들의 속성을 최대한 변경하지 않도록 구현할 예정입니다.
    
    ```java
    public class CommentEntity {
    
        private Long commentId;
        private String content;
        private int like;
        private int dislike;
        private int rating;
        
        private String movieId;     // JPA 에서 ID 만으로 연관관계 가능??
        private UUID userId;        // JPA 에서 ID 만으로 연관관계 가능??
        
        private Instant createdAt;
        
        /* ... */
    }
    ```
    
    위 `Entity` 는 `CachedMovieEntity`, `UserEntity` 와 연관관계를 갖고 있습니다.
    
    이 때 각 `Entity` 의 `ID` 만으로 `JPA` 에서 연관관계가 가능한지 모르겠으나, 이를 `Entity` 로 바꾸면 기존 `Service`, `Controller` 에 수정해야 할 부분이 많아 최대한 기피할 예정입니다.
    
    ~~방법 없으면 해야죠 뭐...~~

- **2. 기존 `Repository` 규약 `(interface)` 에 맞는 `JPA` 구현체를 추가합니다.**

    이전 `MyBatis` 처럼 `JPA` 전용 `Repository` `(MyBatis 로 따지면 mapper 들)` 를 만들고, 이를 주입받는 구현체를 사용할 것 같습니다.

- **3. `JPA` 구현체를 이용해 기존 `Test code` 들이 정상 작동하는지 확인합니다.**

    이전 `Refactoring` 한 `Repository Test Code` 들이 정상 작동하는지 확인합니다.

---

> ## **3. `spring profile` 에 따라 이 둘을 자유롭게 선택할 수 있도록 배포**

- **1. 전체 `Test Code` 들이 정상 작동하는지 확인합니다. (Optional)**

    물론 이를 위해선 다른 `Test Code` 들도 대대적인 `Refactoring` 이 필요합니다. 그래서 이 작업은 시간이 여유롭다면 진행할 것 같습니다.

- **2. `Postman` 등으로 실 작동이 원활한지 확인합니다. (필수)**

    진짜로 테스트 해보면서 정상 작동하는지 확인합니다.

---

# ⏩ 계획 완료 후 예상되는 작업

아직 진행 전 단계라 얼마나 걸릴지 잘 예상되진 않지만, 작업 계획은 늦어도 `~10/26 or 27` 정도로 생각하고 있습니다. 

완료 후, 일손 필요한 곳에 붙어 프로젝트 진행할 것 같습니다.

---

**Comment by jbw9964** [comment]
@jbw9964 @hgh1472 @TrixieL20 @shmin98 @sunnism03 

`JPA` 마이그레이션 계획입니다. 의견이나 궁금한 점 있으면 코멘트 달아주세요.

**Comment by hgh1472** [comment]
찾아보니까 Entity 내의 연관관계를 **객체로 바꾸지 않고 그냥 그대로 key 값으로 진행하는 식**으로 해도 되는 것 같아요!

대신 기존 프로젝트를 유지할 수 있는 장점이 있지만, JPA의 장점 중 하나인 객체 그래프 탐색을 이용하지 못하는 것 같아요.
예를 들어, 리뷰 포스팅으로부터 영화 객체가 필요할 때 JPA의 장점인 `review.getMovie()`가 아닌, `movieRepository.findById(review.getMovieId())`처럼 무비 리포지토리를 필드로 가진 상태에서 이용해야 합니다.

하지만 Entity의 필드를 외래키가 아닌 객체로 할 경우, 코드 수정 비율이 더 많아질 것 같아요! 그래서 **Entity의 필드를 유지시키는 방향이 더 좋을 것 같습니다!**
