### ISSUE TITLE
[Invalid] - 각 `Controller` 에서 `@PathVariable`, `@RequestParam` 에 `name` 속성을 명시해 주세요.

### ISSUE THREAD

**Issue by jbw9964** [prgrms-be-devcourse/NBE1_2_Team10#143]
# ⚠ 요청 개요

- **담당자 : `Controller` 구현한 사람** 
- **중요도 : 중**
- **수정 기한 : `none`** 

---

# 📑 수정이 필요한 내용

1. **위치:** 

각 `Controller` endpoint 중 `@PathVariable`, `@RequestParam` 을 사용한 부분들

2. **현재 상태** 

몇몇 endpoint 는 이들의 이름이 명시되어 있지만 그렇지 않은 메서드가 꽤 존재합니다.

3. **원하는 변경 방향성** 

```java
@PathVariable String movieId
@RequestParam int page
```

```java
@PathVariable(name = "movieId") String movieId
@RequestParam(name = "page") int page
```

---

# ⚔ 변경 요청 사유

이유는 모르겠으나 `API` 요청 시 어쩔땐 잘 수행하지만, 어쩔땐 내부 오류가 발생합니다.

<p align="center">
  <img width="80%" height="80%" alt="스크린샷 2024-10-20 19 43 36" src="https://github.com/user-attachments/assets/ee96133a-c6d4-4192-874f-742bb08e9c90">
</p>

<p align="center">
  <img width="1496" alt="스크린샷 2024-10-20 19 43 41" src="https://github.com/user-attachments/assets/d4c54d13-2afc-4463-b8a4-98e6f840e925">
</p>

저는 대게 모든 프로젝트 cache 를 삭제하고 실행하면 오류가 발생합니다.

---

# 📚 기타 참고 사항

오류에 나와있듯 `Java compile` 옵션에 `-parameter` 를 넣으면 해결되긴 하지만 각 이름을 명시하는게 더 좋을 것 같습니다.

---

**Comment by hgh1472** [comment]
JPA 마이그레이션 진행하면서 해당사항 적용했습니다.
관련한 글이 있어서 링크도 같이 달아놓을게요

[@PathVariable name 생략 질문](https://www.inflearn.com/community/questions/1087879/pathvariable-name-%EC%83%9D%EB%9E%B5-%EC%A7%88%EB%AC%B8-%EB%93%9C%EB%A6%BD%EB%8B%88%EB%8B%A4?srsltid=AfmBOopCDvzvlA_wNVLxX1ii2dDUW0zxOPg_ET7yLjlApC9PF5RvLzNU)
