### ISSUE TITLE
[Bug] `UserRepository`의 Mybatis 구현체의 `findById`가 이상한 것 같아요

### ISSUE THREAD

**Issue by hgh1472** [prgrms-be-devcourse/NBE1_2_Team10#151]
# ❗❗ 발견한 버그에 대한 설명

**어떻게 해당 버그가 발생하는지 명확하게 설명해주세요.**

JPA 리포지토리를 구현한 후 테스트 한 뒤, 기존 마이바티스 구현체도 테스트 코드를 실행했을 때 통과하는지 테스트했습니다.
실패하는 테스트가 `findById`를 사용하는 코드입니다.

![image](https://github.com/user-attachments/assets/2ed92081-dad5-4ca9-8b72-42cbeae7eec6)

혹시 추가적인 설정이 필요하거나 현재 수정중인 내용일까요??
MybatisConfig도 빈으로 등록되도록 하였습니다.

---

# ✅ 정상적인 실행

**정상적으로 실행 시 예측되는 동작에 대해 서술해주세요.**

뭔가 UUID가 DB에 저장되는 값이랑 자바에서 읽어오는 값이랑 다른 것 같아요.
성공하는 테스트는 `findByUserEmail`, `delete`, `findAll` 작업입니다.

---

# 📤 문제 상황 공유

**가능하다면 문제가 된 상황을 보여주는 스크린 샷을 첨부해주세요.**

![image](https://github.com/user-attachments/assets/07ed7518-f919-4dfc-b51f-892d58bbcae1)

![image](https://github.com/user-attachments/assets/86851731-1d6b-4c3e-98ee-dd4b572f304c)

Optional을 get할 때 비어있어서 오류가 발생하고 있습니다

**Comment by jbw9964** [comment]
@hgh1472 어느 브랜치에서 발생했나요?

**Comment by hgh1472** [comment]
@jbw9964 `develop`에서 발생했어요. 혹시 정상적으로 실행되나요???

**Comment by jbw9964** [comment]
확인하니 2 가지 문제점을 파악했습니다.

1. 독립적이지 못한 테스트 코드
테스트 코드에 사용되는 `testUser`, `testUser2` 객체에 직접 타이핑 된 `UUID` 가 들어가는 것을 확인했습니다.

<p align="center">
  <img src="https://github.com/user-attachments/assets/95ef420a-3cc7-4e95-9055-3305df6489b2" width=65% height=65%>
</p>


2. `UUID` fetch 실패(?)
`userRepo.saveNewUser(testUser)` 실행 시 `testUser` 의 `UUID` 가 `DB` 에 저장된 값으로 `fetch` 되지 않는 것을 확인하였습니다.

<p align="center">
  <img src="https://github.com/user-attachments/assets/2590e764-e3eb-43ae-af3e-a246379aa355" >
</p>

`DB` 에는 `8bfb6229-90e5-11ef-ba02-00d861a152a7` 로 저장되었지만 `testUser` 의 `UUID` 는 `991c95d6-808a-11ef-8da5-467268b55380` 그대로인 것을 확인하였습니다.

**Comment by jbw9964** [comment]
`[1]` 은 그렇게 큰 문제가 되지 않지만 `[2]` 는 수정이 필요해 보입니다.

`fetch` 가 되지 않는 이유는 이전 @sunnism03 님께 말씀 드린 적이 있습니다.

`DB` 에 새로 저장시 생성되는 `UUID` 는 `AUTO INCREMENT` 처럼 `generated value` 로 설정될 수 없습니다.
그래서 `default` 구문으로 아래 `DDL` 로 정의되어 있습니다.

```sql
create table user_table
(
    user_id       binary(16)             default (unhex(replace(uuid(), _utf8mb3'-', _utf8mb4''))) not null comment '유저 식별자'
        primary key,
    user_email    varchar(50)                                                                      not null comment '유저 이메일, 로그인 ID 로 이용',
    user_pw       varchar(200)                                                                     not null comment '유저 비밀번호, 인코딩 후 저장',
    user_name     varchar(30)                                                                      not null comment '유저 실명',
    role          enum ('ADMIN', 'USER') default 'USER'                                            not null comment '유저 권한 (관리자, 일반 유저)',
    refresh_token varchar(200)                                                                     null comment '해당 유저에 발급된 리프래쉬 토큰',
    alias         varchar(50)            default (`user_email`)                                    null comment '유저 활동 닉네임, 초기 설정은 이메일과 동일',
    phone_num     varchar(50)                                                                      null comment '전화번호',
    constraint USER_TABLE_pk_2
        unique (user_email)
)
    comment '유저 테이블';
```

문제는 `MyBatis` 에서 `insert` 시 key 값을 가져오는 행위는 `generated value` 에만 가능하다는 점 입니다.
그래서 `UserRepository` 에 `save` 를 진행해도 `testUser` 에 해당 `UUID` 가 가져와 지지 않습니다.

그나마 해결하려면 아래처럼 `UserRepositoryImpl` 에 `saveNewUser` 를 아래처럼 바꿔야 할 것 같습니다.

```java
@Override
public UserEntity saveNewUser(UserEntity newUser) {
    mapper.saveNewUser(newUser);
    return this.findByUserEmail(newUser.getEmail()).orElseThrow();
}
```

**Comment by hgh1472** [comment]
@jbw9964 필드에 있는 testId를 지우고, findByEmail을 통해서 조회하니까 통과하네요. save 호출 후 testUser의 UUID를 찍었을 때 나오길래 제대로 저장된 UUID인 줄 알았는데, 필드에 있는 값이 나오는거였군요
지우고 findByEmail로 확인하니까 되는 것 같아요

**Comment by jbw9964** [comment]
여럿 혼동의 여지가 있으니 `UserRepository#saveNewUser` 를 반환 말고 `UserEntity` 반환으로 바꾸면 더 좋을 것 같습니다!
