### ISSUE TITLE
[Invalid] cached_movie_table 관련 수정 요청

### ISSUE THREAD

**Issue by hgh1472** [prgrms-be-devcourse/NBE1_2_Team10#30]
# ⚠ 요청 개요

- **담당자 :**  hgh1472
- **중요도 :** 상
- **수정 기한 :** 2024-09-29 

---

# 📑 수정이 필요한 내용

1. **위치:** Cached_Movie_Table

2. **현재 상태** 
```sql
create table cached_movie_table
(
    movie_id      varchar(50)      not null comment 'KMDB 영화 ID (알파벳-숫자)'
        primary key,
    title         varchar(100)     not null comment '영화 제목',
    poster_url    varchar(200)     not null comment '영화 포스터 이미지 url',
    dib_count     bigint default 0 not null comment '해당 영화가 찜으로 지정된 수',
    review_count  bigint default 0 not null comment '해당 영화에 달린 리뷰 포스팅 수',
    comment_count bigint default 0 not null comment '해당 영화에 달린 한줄평 수',
    sum_of_rating bigint default 0 not null comment '해당 영화 한줄평의 평점 총 합'
)
```

4. **원하는 변경 방향성** 

- **어떻게 바뀌길 원하는지 구체적으로 적어주세요.**

현재 cached_movie_table 의 경우 위 구조로 되어 있습니다.
메인 페이지에서 찜 많은 순, 평점 높은 순의 경우 cached_movie_table을 통해 조회를 하게 됩니다.
그런데 cached_movie_table에는 개봉일 정보가 저장되어 있지 않아 추가적으로 KMDB API를 사용해야 하는 상황입니다.
그래서 차라리 저희가 상세페이지에 해당하는 정보까지 cached_movie_table에 저장하는 것은 어떨까요?

```sql
create table cached_movie_table
(
  create table cached_movie_table
(
    movie_id      varchar(50)      not null comment 'KMDB 영화 ID (알파벳-숫자)'
        primary key,
    title         varchar(100)     not null comment '영화 제목',
    poster_url    varchar(200)     not null comment '영화 포스터 이미지 url',
    genre         varchar(50)      not null comment '영화 장르',
    release_date  varchar(30)      not null comment '영화 개봉일',
    plot          text             not null comment '영화 줄거리',
    running_time  varchar(10)      not null comment '영화 상영시간',
    actors        varchar(180)     not null comment '출연 배우 5명',
    director      varchar(30)      not null comment '감독',
    dib_count     bigint default 0 not null comment '해당 영화가 찜으로 지정된 수',
    review_count  bigint default 0 not null comment '해당 영화에 달린 리뷰 포스팅 수',
    comment_count bigint default 0 not null comment '해당 영화에 달린 한줄평 수',
    sum_of_rating bigint default 0 not null comment '해당 영화 한줄평의 평점 총 합'
)
)

```

배우의 경우, 그냥 하나의 String으로 저장하는 식으로 작성했습니다.

`마동석, 김무열, 박지환, 이동휘, 이범수`

저희가 배우 테이블을 따로 쓰지 않아 정규화시키기에는 작업이 길어질 것 같아서 하나의 String으로 작성하는 것으로 생각했습니다.

---

# ⚔ 변경 요청 사유

**변경을 요청하는 구체적인 이유를 설명해주세요.**

만약 cached_movie_table을 상세페이지에 해당하는 정보를 포함하도록 변경 시, 메인 페이지의 찜 많은 순, 평점 높은 순의 경우
로직 뿐만 아니라 성능상으로도 더 좋을 것 같습니다.
또한 상세페이지에서도 현재 구조라면 KMDB API로 조회하고 cached_movie_table을 통해 찜 개수와 평점을 가져와야 합니다.
하지만 변경하게 되면 cached_movie_table에서 영화에 대해 조회하고 있다면 그 데이터를 바로 보내주고, 없을 시에 KMDB API에 조회하면 되기 때문에 더 좋을 것 같습니다.

---

# 📚 기타 참고 사항

**이 요청과 관련된 추가적인 정보나 참고하면 좋을 사이트 링크 등을 여기에 기재해주세요.**

---

**Comment by jbw9964** [comment]
만약 그렇다면 어떤 케이스에 `cached_movie_table` 정보를 저장하게 될까요?

기존에는 유저가 `영화를 찜`, `한줄평 댓글 작성`, `후기 포스팅 작성` 시에 저장하도록 했는데,
위 방법은 `유저가 특정 영화의 상세페이지에 접속` 할 때도 추가되어야 하나요?

**Comment by hgh1472** [comment]
@jbw9964
저장하는 상황까지는 생각 못해본 것 같아요. `상세 페이지 접속`도 추가하면 `KMDB API` 사용은 크게 줄 것 같긴 하네요!

**Comment by TrixieL20** [comment]
메인 페이지에서 보여줄 영화들도 캐시 테이블에 저장한 필요한 상황 중 하나인 것 같아요!
