### ISSUE TITLE
[Invalid] - `ReviewRepository` mapper 의 위치와 선언이 이상합니다.

### ISSUE THREAD

**Issue by jbw9964** [prgrms-be-devcourse/NBE1_2_Team10#60]
# ⚠ 요청 개요

- **담당자 : 도윤** 
- **중요도 : 중**
- **수정 기한 : ASP** 

---

# 📑 수정이 필요한 내용

1. **위치:**
 - **develop 브랜치 - [`application/src/main/resources/mappers.review/ReviewMapper.xml`](https://github.com/prgrms-be-devcourse/NBE1_2_Team10/blob/develop/application/src/main/resources/mappers.review/ReviewMapper.xml)**
 - **develop 브랜치 - [`application/src/main/java/core/application/reviews/repositories/mapper/ReviewMapper.java`](https://github.com/prgrms-be-devcourse/NBE1_2_Team10/blob/develop/application/src/main/java/core/application/reviews/repositories/mapper/ReviewMapper.java)**

---

2. **현재 상태** 

- `mappers.review/ReviewMapper.xml`

다른 `mapper` 들은 `mappers` 폴더에 들어가 있지만 해당 파일은 `mappers.review` 라는 폴더에 저장되어 있습니다.
통일성을 위해 `mappers/review/ReviewMapper.xml` 로 변경했으면 좋겠습니다.

[수정 전]
```
│   application.properties
│   
├───mappers
│   ├───movies
│   │       CacheMovieMapper.xml
│   │       
│   ├───review
│   └───users
│           DibMapper.xml
│           UserMapper.xml
│           
├───mappers.review
│       ReviewMapper.xml
│       
└───privates
        private.properties
```

[수정 후]
```
│   application.properties
│
├───mappers
│   ├───movies
│   │       CacheMovieMapper.xml
│   │
│   ├───review
│   │       ReviewMapper.xml
│   │
│   └───users
│           DibMapper.xml
│           UserMapper.xml
│
└───privates
        private.properties
```

- `ReviewMapper.java`
`ReviewMapper` 가 `extend ReviewRepository` 하지 않아 어플리케이션 실행 시 자꾸 bean configuration fail 에러가 발생합니다.

[수정 전]
```java
@Mapper
public interface ReviewMapper {
    // 생략
}
```

[수정 후]
```java
@Mapper
public interface ReviewMapper extends ReviewRepository {
    // 생략
}
```

---

# ⚔ 변경 요청 사유

어플리케이션 실행 or 테스트 시 자꾸 bean 생성 에러가 발생합니다.

---

# 📚 기타 참고 사항

**이 요청과 관련된 추가적인 정보나 참고하면 좋을 사이트 링크 등을 여기에 기재해주세요.**

---

**Comment by hgh1472** [comment]
저는 그거보고 review만 디렉토리가 왜 구분되어있지 했는데 디렉토리명 자체가 `mappers.review`로 되어있던거군요..!
